name: Continuous Integration

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-ci
  cancel-in-progress: true

jobs:

  vars:
    name: Checks and variables
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Output Variables
        id: vars
        run: |
          echo "::set-output name=version::$(grep "VERSION = " Makefile | cut -d " " -f 3)"
      - name: Setup Golang Environment
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Check if CRDs changed
        run: |
          make update-crds && git diff --name-only --exit-code deploy/manifests/crds/*

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    needs: vars
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Golang Environment
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Run Tests
        run: make unit-test
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: cover-${{ github.run_id }}.html
          path: ${{ github.workspace }}/cover.html
        if: always()

  njs-unit-tests:
    name: NJS Unit Tests
    runs-on: ubuntu-20.04
    needs: vars
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm --prefix ${{ github.workspace }}/internal/nginx/modules install
      - run: npm --prefix ${{ github.workspace }}/internal/nginx/modules test

  binary:
    name: Build Binary
    runs-on: ubuntu-20.04
    needs: vars
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Golang Environment
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Build Binary
        run: make build
      - name: Cache Artifacts
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/build/.out/gateway
          key: nginx-kubernetes-gateway-${{ github.run_id }}-${{ github.run_number }}

  build:
    name: Build Image
    runs-on: ubuntu-20.04
    needs: [vars, binary]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Fetch Cached Artifacts
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/build/.out/gateway
          key: nginx-kubernetes-gateway-${{ github.run_id }}-${{ github.run_number }}
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name=ghcr.io/nginxinc/nginx-kubernetes-gateway
          tags: |
            type=semver,pattern={{version}}
            type=edge
            type=ref,event=pr
            type=ref,event=branch,enable=${{ startsWith(github.ref, 'refs/heads/release') }}
          flavor: |
            latest=true
      - name: Build Image Debian
        uses: docker/build-push-action@v3
        with:
          file: build/Dockerfile
          context: '.'
          target: local
          tags: ${{ steps.meta.outputs.tags }}
          load: ${{ !startsWith(github.ref, 'refs/tags') }}
          push: ${{ startsWith(github.ref, 'refs/tags') }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ needs.vars.outputs.version }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.2.3
        continue-on-error: true
        with:
          image-ref: ghcr.io/nginxinc/nginx-kubernetes-gateway:${{ steps.meta.outputs.version }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-nginx-kubernetes-gateway.sarif'
          ignore-unfixed: 'true'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        continue-on-error: true
        with:
          sarif_file: 'trivy-results-nginx-kubernetes-gateway.sarif'
      - name: Upload Scan Results
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: 'trivy-results-nginx-kubernetes-gateway.sarif'
          path: 'trivy-results-nginx-kubernetes-gateway.sarif'
        if: always()
